### ISSUE TITLE
Feature Request: Implement Nox Integration for Importing Resources into Digital ID

### ISSUE THREAD

**Issue by RasmusSlothJensen** [Triple-Arm-Technique-ApS/DigitalIDIssues#269]
#### Description
Develop the functionality to import resources from Nox into Digital ID. This feature will enable the seamless transfer of data from Nox to Digital ID.

**Comment by L4hibYoussef** [comment]
SQL
bruger idcsa
pw Idc2730fargo
192.168.1.207 Lokal bruger er idcadmin
pw Idc2730fargo

**Comment by L4hibYoussef** [comment]
[NOX SIMScodesAutoUpdate_SIMSV6.pdf](https://github.com/Triple-Arm-Technique-ApS/DigitalIDIssues/files/15330853/NOX.SIMScodesAutoUpdate_SIMSV6.pdf)
