### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by L4hibYoussef** [Triple-Arm-Technique-ApS/DigitalIDIssues#337]
When creating applicants in a Resource. After clicking add the front end fails with this error.

**Comment by L4hibYoussef** [comment]
The issue also happens when reaching the last view where you have to add name and displayname and then clicking out the side panel

**Comment by RasmusJannerup** [comment]
Found the issues, when closing the slideover the parent in AddApplicantSlideOverContext is set to undefined, which causes the error. Will be fixed in the branch 335-email-signin-and-invitations
